services:
  server:
    image: server
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      HOST: ${HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: psql
      DB_PORT: 5432
    ports:
      - "${WEB_PORT}:8080"
    depends_on:
      psql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "./healthcheck"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s

  psql:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  psql_volume:
