// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findAuthById = `-- name: FindAuthById :one
SELECT a.id, user_id, source, access_token, expires_in, refresh_token, rt_expires_in, u.id, username, masterkey, b64salt, b64filekey FROM "Auth" a
JOIN "User" u on u.id = a.user_id
WHERE a.id = $1
LIMIT 1
`

type FindAuthByIdRow struct {
	ID           int32
	UserID       pgtype.Int4
	Source       pgtype.Text
	AccessToken  pgtype.Text
	ExpiresIn    pgtype.Float8
	RefreshToken pgtype.Text
	RtExpiresIn  pgtype.Float8
	ID_2         int32
	Username     string
	Masterkey    pgtype.Text
	B64salt      pgtype.Text
	B64filekey   pgtype.Text
}

func (q *Queries) FindAuthById(ctx context.Context, id int32) (FindAuthByIdRow, error) {
	row := q.db.QueryRow(ctx, findAuthById, id)
	var i FindAuthByIdRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.AccessToken,
		&i.ExpiresIn,
		&i.RefreshToken,
		&i.RtExpiresIn,
		&i.ID_2,
		&i.Username,
		&i.Masterkey,
		&i.B64salt,
		&i.B64filekey,
	)
	return i, err
}

const findAuthByUserId = `-- name: FindAuthByUserId :one
SELECT id, user_id, source, access_token, expires_in, refresh_token, rt_expires_in FROM "Auth"
WHERE user_id = $1 AND source = $2
LIMIT 1
`

type FindAuthByUserIdParams struct {
	UserID pgtype.Int4
	Source pgtype.Text
}

func (q *Queries) FindAuthByUserId(ctx context.Context, arg FindAuthByUserIdParams) (Auth, error) {
	row := q.db.QueryRow(ctx, findAuthByUserId, arg.UserID, arg.Source)
	var i Auth
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.AccessToken,
		&i.ExpiresIn,
		&i.RefreshToken,
		&i.RtExpiresIn,
	)
	return i, err
}

const persistAuth = `-- name: PersistAuth :exec
INSERT INTO "Auth" (
    id, user_id, source, access_token, expires_in, refresh_token, rt_expires_in
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT DO NOTHING
`

type PersistAuthParams struct {
	ID           int32
	UserID       pgtype.Int4
	Source       pgtype.Text
	AccessToken  pgtype.Text
	ExpiresIn    pgtype.Float8
	RefreshToken pgtype.Text
	RtExpiresIn  pgtype.Float8
}

func (q *Queries) PersistAuth(ctx context.Context, arg PersistAuthParams) error {
	_, err := q.db.Exec(ctx, persistAuth,
		arg.ID,
		arg.UserID,
		arg.Source,
		arg.AccessToken,
		arg.ExpiresIn,
		arg.RefreshToken,
		arg.RtExpiresIn,
	)
	return err
}
