// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Auth struct {
	ID           int32
	UserID       int32
	Source       string
	AccessToken  pgtype.Text
	ExpiresIn    pgtype.Float8
	RefreshToken pgtype.Text
	RtExpiresIn  pgtype.Float8
}

type File struct {
	OwnerID    int32
	Source     string
	Reponame   string
	Filename   string
	B64content pgtype.Text
	B64nonce   pgtype.Text
}

type User struct {
	ID         int32
	Username   string
	Masterkey  pgtype.Text
	B64salt    pgtype.Text
	B64filekey pgtype.Text
}
